package model;

public enum RequestType {LOGIN, LOGOUT, REGISTER, GET_USER_INFO, 
		CREATE_CONVERSATION, CREATE_GROUP_CONVERSATION, GET_CONVERSATION,
		ADD_PARTICIPANT, REMOVE_PARTICIPANT, SEND_MESSAGE, GET_MESSAGES, GET_NEW_MESSAGES};
