package model;

public class RequestType {
	public enum requestType {LOGIN, LOGOUT, REGISTER, GET_USER_INFO, 
		CREATE_CONVERSATION, CREATE_GROUP_CONVERSATION, GET_CONVERSATION,
		ADD_PARTICIPANT, REMOVE_PARTICIPANT, SEND_MESSAGE, GET_MESSAGE, GET_NEW_MESSAGE};
}
