package model;

public enum ResponseType { LOGIN_SUCCESS, LOGIN_FAIL, LOGOUT_SUCCESS, LOGOUT_FAIL, 
	REGISTER_USER_SUCCESS, REGISTER_USER_FAIL, USER_INFO_SENT, USER_INFO_NOT_SENT, 
	MESSAGE_SENT, MESSAGE_NOT_SENT, SENDING_MESSAGE,ADD_PARTICIPANT_SUCCESS, 
	ADD_PARTICIPANT_FAIL, REMOVE_PARTICIPANT_SUCCESS, REMOVE_PARTICIPANT_FAIL,
	GROUP_CREATION_SUCCESS, GROUP_CREATION_FAIL, CREATE_CONVERSATION_SUCCESS, CREATE_CONVERSATION_FAIL, 
	CONVERSATION_SENT, CONVERSATION_SENT_NOT_SENT, ACTIVE_CONVERSATION_UPDATED, SENDING_DATA
	}
