package model;

public enum ResponseType { LOGIN_SUCCESS, LOGIN_FAIL, LOGOUT_SUCCESS, LOGOUT_FAIL, 
	REGISTER_USER_SUCCESS, REGISTER_USER_FAIL, MESSAGE_SENT, MESSAGE_NOT_SENT, 
	ADD_PARTICPANT_SUCCESS, ADD_PARTICIPANT_FAIL, REMOVE_PARTICIPANT_SUCCESS, REMOVE_PARTICIPANT_FAIL,
	GROUP_CREATION_SUCCESS, GROUP_CREATION_FAIL
	}
