package model;

public enum ResponseType {
    LOGIN_SUCCESS, LOGIN_FAIL, LOGOUT_SUCCESS, LOGOUT_FAIL,
    REGISTER_USER_SUCCESS, REGISTER_USER_FAIL, USER_INFO_SENT, USER_INFO_NOT_SENT,
    MESSAGE_SENT, MESSAGE_NOT_SENT, SENDING_MESSAGE, ADD_PARTICIPANT_SUCCESS,
    ADD_PARTICIPANT_FAIL, REMOVE_PARTICIPANT_SUCCESS, REMOVE_PARTICIPANT_FAIL,
    GROUP_CREATION_SUCCESS, GROUP_CREATION_FAIL, CREATE_CONVERSATION_SUCCESS, CREATE_CONVERSATION_FAIL,
    CONVERSATION_SENT, CONVERSATION_NOT_SENT, ACTIVE_CONVERSATION_UPDATED,
    SENDING_CONVERSATION_DATA, SENDING_USER_DATA, SENDING_MESSAGE_DATA, DATA_RECEIVED, DATA_NOT_RECEIVED,
    USER_LOGGED_IN, USER_LOGGED_OUT, PARTICIPANT_ADDED, PARTICIPANT_REMOVED,
    CONVERSATION_LOG_QUERY_RESULT, CONVERSATION_LOG_SENT, CONVERSATION_LOG_NOT_SENT, GROUP_NAME_CHANGED
}