@startuml
title Use Case 2: Logging Out

actor User
boundary GUI as "Client GUI"
control Client as "Client App"
control Server as "Server"

== Logout ==
User -> GUI: Click "Logout"
GUI -> Client: Logout requested
Client --> Server: Send User data
Client -> Client: Flush locally stored data\n(user data, conv data)
Client -> GUI: Return to Login Screen
@enduml
