@startuml
title Use Case 6: Group Chat Functionality

actor User
boundary GUI as "Client GUI"
control Client as "Client App"
control Server as "Server"
collections ClientCache as "Client Cache\n(User directory + Conversation headers)"
collections Cache as "Server Cache\n(Users + Conversation headers)"
collections Store as "Server Persistent Storage\n(Conversation headers)"

== Create group conversation ==
User -> GUI: From a conversation, select Convert to Group Conversation

Client -> Server: CreateGroupConversation(currentConversation)
Server -> Store: Create conversation file
Store --> Server: Created (conversationId)
Server -> Cache: Update conversation logs
Server --> Client: CreateConversation OK

Client -> ClientCache: Add conversation to local
Client -> GUI: Open new group conversation view

== Add users later ==
loop When Group Chat Creator adds participants
  User -> GUI: Choose "Add Members"
  ref over User, GUI, Client, Server: Searching For A User
  User -> GUI: Select user to add\nClick "Add"
  GUI -> Client: AddParticipant(userIdToAdd)
  Client -> Server: AddParticipant(userIdToAdd)

  Server -> Cache: Update participants list\n(add user)

  Server --> Client: AddParticipants OK

  == Notify logged-in participants ==
  ref over Client, Server, Cache : Push User Added Message to other participants 
end
== Remove Users ==
loop When Group Chat Creator Removes participants
 User -> GUI: Select "Remove Members" 
 GUI -> User: Display List of Participands
 User -> GUI: Select User to Remove
 GUI -> Client: RemoveUser(UserID)
 Client -> Server: RemoveUser(UserID)
 Server -> Cache: Update Particiapnts list\n(remove user)
 Server --> Client: LeaveConversation OK
 == Notify remaining participants ==
 ref over Client, Server, Cache : Push User Removed Message to other participants 
end

== Leave group conversation ==
User -> GUI: Choose "Leave Group"
GUI -> Client: LeaveConversation(conversationId)
Client -> Server: RemoveParticipant(conversationId)

Server -> Cache: Update participants list\n(remove user)
Server --> Client: LeaveConversation OK

== Notify remaining participants ==
ref over Client, Server, Cache : Push User Left Message to other participants 


Client -> ClientCache: Remove/mark conversation\nas left for this user
Client -> GUI: Close conversation view\nReturn to conversation list
@enduml
